export type Article = {
  slug: string;
  title: string;
  description: string;
  category: string;
  audience: string;
  intent: string;
  sections: { heading: string; body: string[] }[];
  checklist?: readonly string[];
};

const speed = [
  { heading: 'The practical answer', body: ['Most home-service buyers are not casually browsing. A broken AC, leaking pipe, peeling exterior, pest issue, dirty rental, or storm-damaged roof creates urgency. The company that replies clearly while the problem is still fresh usually gets the first real conversation.', 'Speed-to-lead is not just answering fast. It is answering with the right next step: confirm the request, collect missing details, set expectations, and make booking feel easy.'] },
  { heading: 'What to say first', body: ['Use a short message that confirms the job type, location, timing, and next step. Example: “Thanks for reaching out. I can help with that. What is the property address, and are you hoping to get this looked at today, this week, or just planning ahead?”', 'This works because it is fast, useful, and low-pressure. It turns a vague inquiry into a qualified lead.'] },
  { heading: 'Where LeadSprint fits', body: ['LeadSprint helps small home-service teams keep fast-response scripts, quote follow-ups, customer notes, and lead stages in one lightweight workflow, so good opportunities do not disappear in texts, missed calls, and inbox tabs.'] },
];
const follow = [
  { heading: 'The practical answer', body: ['A good follow-up system is polite, specific, and timed around the customer’s decision. Many homeowners are not ignoring you because they are uninterested. They are comparing options, waiting on a spouse, dealing with work, or unsure what the next step is.', 'The goal is to make the next step obvious without sounding desperate or pushy.'] },
  { heading: 'A simple follow-up rhythm', body: ['Send the first follow-up the same day as the estimate, another the next day, another after three days, and a final helpful check-in about a week later. For larger jobs, add a two-week value-based follow-up that answers a common concern.', 'Each touch should add clarity: timing, scope, availability, warranty, prep, payment, or what happens after approval.'] },
  { heading: 'Where LeadSprint fits', body: ['LeadSprint gives owners ready-to-use SMS, email, and call script patterns, plus lead statuses like New, Qualified, Quoted, Followed up, Won, and Lost, so every open quote has a visible next step.'] },
];
const quote = [
  { heading: 'The practical answer', body: ['Quote conversion improves when the customer understands the scope, trusts the company, and knows exactly how to move forward. A quote with no follow-up asks the customer to do all the work.', 'A better quote process explains what is included, what could change, when the work can happen, and how to approve the job.'] },
  { heading: 'What to include after the estimate', body: ['Send a short note that summarizes the job, reinforces the value, and gives one clear next step. Example: “I sent the estimate for the project. It includes prep, materials, labor, and cleanup. If you want to reserve the next opening, reply APPROVE and I’ll send the deposit link.”', 'This kind of follow-up removes friction and makes the quote feel professional.'] },
  { heading: 'Where LeadSprint fits', body: ['LeadSprint helps turn estimates into organized opportunities with follow-up prompts, objection responses, deposit language, and reminders that keep quoted work from going quiet.'] },
];
const pipeline = [
  { heading: 'The practical answer', body: ['A small home-service company does not always need a heavy CRM. It does need one reliable place to see who reached out, who needs a quote, who has been followed up with, and who is ready to book.', 'The best system is the one the owner or office manager will actually use during a busy week.'] },
  { heading: 'The core stages', body: ['Use simple stages: New, Qualified, Quoted, Followed up, Won, and Lost. Add source, job type, next follow-up date, estimate amount, and the next action. That is enough to stop most leads from slipping through the cracks.', 'Do not overbuild the workflow before the basics are consistent.'] },
  { heading: 'Where LeadSprint fits', body: ['LeadSprint is built for that simple operating rhythm: capture the lead, qualify the job, send the quote, follow up, and keep the pipeline moving without turning the business into a software project.'] },
];

const raw = [
  ['what-is-speed-to-lead-home-services','What Is Speed to Lead for Home-Service Businesses?','Learn why fast lead response matters for contractors, cleaners, landscapers, painters, plumbers, HVAC companies, and other local service teams.','Speed to lead','Owners and office managers','Informational',speed,['Reply within 5 minutes when possible','Confirm service type, location, urgency, and contact details','Give one clear next step','Log the lead immediately','Schedule the follow-up before moving on']],
  ['best-follow-up-schedule-home-service-leads','The Best Follow-Up Schedule for Home-Service Leads','A practical follow-up cadence for new inquiries, open estimates, and quiet prospects.','Follow-up','Busy home-service teams','Informational',follow,['Same day: confirm and clarify','Day 1: answer the most likely question','Day 3: restate value and availability','Day 7: final helpful check-in','Day 14: larger-job value follow-up']],
  ['home-service-follow-up-templates','Home-Service Follow-Up Templates: SMS, Email, and Call Scripts','Copy-and-adapt follow-up messages for leads, quotes, objections, quiet prospects, and review requests.','Templates','Contractors and service businesses','Template',follow,['New lead text','Estimate sent text','Quiet lead check-in','Price objection response','Review request after job completion']],
  ['track-home-service-leads-without-crm','How to Track Home-Service Leads Without a Complicated CRM','A simple lead tracking workflow for small home-service businesses that do not want bloated software.','Lead management','Small teams and solo operators','Commercial investigation',pipeline,['Lead name and contact info','Job type and location','Lead source','Current stage','Next follow-up date','Estimated value']],
  ['why-customers-dont-respond-after-quote','Why Customers Don’t Respond After You Send a Quote','The common reasons estimates go quiet and how to follow up in a way that earns the next conversation.','Quote conversion','Estimators and owners','Problem solving',quote,['The scope was unclear','They are comparing bids','The next step was vague','They need timing reassurance','They do not yet trust the company']],
  ['first-text-after-quote-request','The First Text Message to Send After a New Quote Request','The first reply can decide whether a paid lead turns into a booked appointment. Here is what to say.','Speed to lead','Home-service teams buying leads','Template',speed,['Thank them','Confirm the service need','Ask for address or service area','Ask about urgency','Offer the next step']],
  ['how-many-times-follow-up-quote-lead','How Many Times Should You Follow Up With a Quote Lead?','A practical answer for contractors who want to win more jobs without annoying prospects.','Follow-up','Service business owners','Informational',follow,['Follow up 3 to 5 times for normal jobs','Use more value, not more pressure','Stop when the prospect clearly declines','Keep tone helpful and specific']],
  ['turn-more-estimates-into-booked-jobs','How to Turn More Estimates Into Booked Jobs','Improve estimate close rates with clearer quotes, better timing, and consistent follow-up.','Quote conversion','Owners and sales teams','Commercial investigation',quote,['Clarify scope','Explain timing','Make approval easy','Follow up with useful reminders','Track won and lost reasons']],
  ['simple-lead-management-system-home-services','Simple Lead Management System for Small Home-Service Businesses','The lightweight pipeline every local service company can use to stop losing opportunities.','Lead management','Solo operators and small crews','Commercial investigation',pipeline,['New','Qualified','Quoted','Followed up','Won','Lost']],
  ['lead-follow-up-templates-painters','Lead Follow-Up Templates for Painters','SMS and email follow-up ideas for interior, exterior, cabinet, and commercial painting leads.','Industry templates','Painting companies','Template',follow,['Ask about rooms, surfaces, timeline, and access','Mention prep and cleanup','Reassure on materials and finish quality','Follow up around weather for exterior work']],
  ['lead-follow-up-templates-plumbers','Lead Follow-Up Templates for Plumbers','Practical lead response and follow-up scripts for plumbing repair, installs, and urgent service calls.','Industry templates','Plumbing companies','Template',speed,['Confirm issue and urgency','Ask about shutoff status for leaks','Offer arrival window','Follow up after diagnosis or estimate']],
  ['lead-follow-up-templates-hvac','Lead Follow-Up Templates for HVAC Companies','Follow-up scripts for HVAC repair, replacement estimates, maintenance plans, and seasonal demand.','Industry templates','HVAC companies','Template',follow,['Separate emergency repair from replacement','Ask about system age','Mention comfort, efficiency, and availability','Follow up before weather spikes']],
  ['lead-follow-up-templates-landscapers','Lead Follow-Up Templates for Landscapers','Follow-up templates for lawn care, cleanups, installs, hardscapes, and recurring maintenance.','Industry templates','Landscapers','Template',follow,['Ask about property size and goals','Clarify one-time vs recurring work','Use seasonal timing','Follow up with scheduling windows']],
  ['lead-follow-up-templates-roofers','Lead Follow-Up Templates for Roofers','Lead response and quote follow-up scripts for roof repair, replacement, leaks, and storm damage.','Industry templates','Roofing companies','Template',quote,['Ask about leak or damage urgency','Mention inspection process','Clarify insurance or out-of-pocket timing','Follow up with materials and scheduling details']],
  ['lead-follow-up-templates-cleaning-businesses','Lead Follow-Up Templates for Cleaning Businesses','Simple follow-up messages for residential, move-out, recurring, and commercial cleaning leads.','Industry templates','Cleaning businesses','Template',speed,['Ask about property size','Clarify one-time or recurring cleaning','Mention access and priorities','Follow up with booking options']],
  ['lead-follow-up-templates-handyman','Lead Follow-Up Templates for Handyman Services','Scripts for handyman leads where the job scope is often vague and needs fast qualification.','Industry templates','Handyman services','Template',pipeline,['Ask for photos','Clarify task list','Group small jobs together','Set minimum service expectations','Follow up with appointment options']],
  ['lead-follow-up-templates-pest-control','Lead Follow-Up Templates for Pest Control Companies','Follow-up scripts for pest issues where urgency, reassurance, and recurring prevention matter.','Industry templates','Pest control companies','Template',speed,['Identify pest type','Ask about severity and location','Explain inspection/treatment next step','Follow up on prevention plan']],
  ['crm-alternative-small-home-service-business','Best CRM Alternative for Small Home-Service Businesses','When a full CRM is too much, a lightweight lead follow-up system may be the better fit.','Comparison','CRM shoppers','Commercial',pipeline,['Choose simple if you mainly need intake, quotes, follow-up, and stages','Choose a full CRM if you need dispatch, complex automations, and large-team reporting']],
  ['quote-follow-up-software-home-services','Quote Follow-Up Software for Home-Service Businesses','What to look for in tools that help contractors and local service teams follow up after estimates.','Software','Buyers comparing tools','Commercial',quote,['Fast templates','Lead stages','Follow-up reminders','Trade-specific language','Simple setup']],
  ['speed-to-lead-software-home-services','Speed-to-Lead Software for Home-Service Companies','How software can help small teams answer faster, organize inquiries, and recover more paid leads.','Software','Owners buying leads','Commercial',speed,['Quick response scripts','Lead capture','Mobile-friendly workflow','Follow-up schedule','Simple reporting']],
] as const;

export const articles: Article[] = raw.map(([slug,title,description,category,audience,intent,sections,checklist]) => ({ slug, title, description, category, audience, intent, sections, checklist }));

export function getArticle(slug: string) {
  return articles.find((article) => article.slug === slug);
}
